### ISSUE TITLE
What's the configuration WSL.REFINE_MIST for?

### ISSUE THREAD

**Issue by anlimo1510** [shenyunhang/UWSOD#3]
Hi,
Thanks for your interesting works. I'm wondering which part of your paper is related to the implement when WSL.REFINE_MIST is True.

**Comment by shenyunhang** [comment]
Hi, thanks for your interest.
This part is not described in our paper.
It is a small variant of MIST ( In Section 4.1 of paper "Instance-aware, context-focused, and memory-efficient weakly supervised object detection").

**Comment by anlimo1510** [comment]
thanks for your reply.
